### ISSUE TITLE
generae not working

### ISSUE THREAD

**Issue by nagkumar** [benefitcloud/ember-cli-uploader#8]
C:\temp\hw\uploader>ember generate ember-cli-uploader
version: 1.13.13
installing ember-cli-uploader
  install bower package ember-uploader
Cannot find module 'bower-art-resolver'
Error: Cannot find module 'bower-art-resolver'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at C:\temp\hw\uploader\node_modules\bower\lib\core\resolverFactory.js:60:42
    at Array.map (native)
    at C:\temp\hw\uploader\node_modules\bower\lib\core\resolverFactory.js:58:46
    at C:\temp\hw\uploader\node_modules\bower\lib\core\resolverFactory.js:35:24
    at _fulfilled (C:\temp\hw\uploader\node_modules\bower\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\temp\hw\uploader\node_modules\bower\node_modules\q\q.js:863:30)

**Comment by digitaltoad** [comment]
I'm in the process of updating this library to be compatible with the newest versions of Ember and Ember CLI. I'm hoping to push out a new version over the holidays.

**Comment by digitaltoad** [comment]
Try the new master at [ember-uploader](https://github.com/benefitcloud/ember-uploader) which deprecates this bridging add-on.
